command: ['node', 'server.js']

# Environment variables - Option 1: Direct values (for testing)
# Replace with your actual values or use Option 2 (secrets) for production

# env:
#   - name: DATABRICKS_HOST
#     value: 'your-databricks-server-hostname'
#   - name: DATABRICKS_HTTP_PATH
#     value: 'your-databricks-http-path'
#   - name: DATABRICKS_ACCESS_TOKEN
#     value: 'your-databricks-access-token'
#   - name: PORT
#     value: '3000'

# Use Databricks Secrets - Add resources via Databricks UI first
# Then reference them here using valueFrom
# env:
#   - name: DATABRICKS_HOST
#     valueFrom: databricks_server_hostname
#   - name: DATABRICKS_HTTP_PATH
#     valueFrom: databricks_http_path
#   - name: DATABRICKS_ACCESS_TOKEN
#     valueFrom: databricks_access_token
#   - name: PORT
#     value: '3000'

